extern int my_strlen(const char*);
extern char* my_strchr(char*, char);
extern void* my_memset(void*, int , long);
extern void* my_memcpy(void * , const void* , long );
extern int my_strcmp(char*, char*);
extern void *my_memmove(void *, const void *, long );
extern int my_strncmp(const char*, const char*, long);
extern int my_strcasecmp(const char*, const char*);
extern char* my_index(char*, char);
extern int my_read(int, void*, long);
extern int my_write(int, void*, long);